[all]

# UART Configuration for GPIO 14/15
enable_uart=0
dtparam=uart0=on
dtoverlay=disable-bt

# SPI for IOL HAT
dtparam=spi=on
dtoverlay=spi0-2cs

# HDMI for 7-inch display
hdmi_force_hotplug=1
hdmi_drive=2
hdmi_group=2
hdmi_mode=87
hdmi_cvt=1024 600 60 6 0 0 0
