[all]

# UART Configuration for GPIO 14/15
enable_uart=0
dtparam=uart0=on
dtoverlay=disable-bt

# SPI for IOL HAT
dtparam=spi=on
dtoverlay=spi0-2cs

# HDMI defaults
hdmi_force_hotplug=1
hdmi_drive=2
hdmi_group=1
hdmi_mode=34
